Selamat pagi, siang, malam dan dini hari.<br/>

Jumpa lagi dengan tutorial dari&nbsp;<a href="https://apolbox.blogspot.com/?m=1" target="_blank">apolbox</a>,
pada kesempatan kali ini saya akan berbagi caranya install phpMyAdmin di Android kita, untuk melanjutkan tutorial sebelumnya yaitu:
<a href="https://apolbox.blogspot.com/2018/09/cara-membuat-webserver-diandroid.html">Tutorial menjalankan localhost di Android.</a><br/>

Emang bisa install phpMyAdmin di android?<br/>
Jawabannya sangat <b>bisa</b>.<br/>

Oke tanpa berlama-lama mari kita mulai tutorialnya.
<ul>
    <li>Buka aplikasi termux dan masuk difolder termux-webserver dengan perintah dibawah ini:</li>
    <pre style="background: #f2f2f2; border-radius: 2px; padding: 12px; width: auto;">
        $ cd termux-webserver
        $ curl -s https://raw.githubusercontent.com/apolbox/termux-webserver/dev/update > ./update
        $ chmod +x ./update
        $ ./update
    </pre>
</ul>